<a href="https://colab.research.google.com/github/Khushi-Kumari947/NLP/blob/main/Text_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# We have different approach
#1.Heuristic approach
#2.API-Provided by company
#3.ML-for vectorization(BOW,TFIDF,N-GRAM,WordVec),model-Naive bayes,SVM,Rnadom forest etc
#4.DL-Rnn(Lstm),CNN,Pretrained--BERT

# Using ML approach

In [6]:
import numpy as np
import pandas as pd

In [7]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews

In [10]:
df=pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')

In [11]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [12]:

new_df=df.iloc[:10000]

In [14]:
new_df.sample(3)

                                                 review sentiment
363   The plot: Michael Linnett Connors has done eve...  positive
5434  It's a male bashing bonanza. I saw this on Sci...  negative
4720  A message movie, but a rather good one. Outsta...  positive

In [15]:
new_df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [19]:
new_df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [22]:
new_df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [25]:
new_df.duplicated().sum()

np.int64(17)

In [26]:
new_df.drop_duplicates(inplace=True)

/tmp/ipykernel_1448/2373844780.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.drop_duplicates(inplace=True)

In [27]:
new_df.duplicated().sum()

np.int64(0)

In [28]:
 #Basic preprocessing

In [30]:
#remove tags
#change to lowercase
#remove stopwords

In [31]:
import re
def remove_tags(raw_text):
  cleaned_text=re.sub(re.compile('<.*?>'),'',raw_text)
  return cleaned_text

In [33]:
new_df['review']=new_df['review'].apply(remove_tags)

/tmp/ipykernel_1448/989152410.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['review']=new_df['review'].apply(remove_tags)

In [37]:
new_df['review'][189]

'I don\'t believe there has ever been a more evil or wicked television program to air in the United States as The 700 Club. They are today\'s equivalent to the Ku Klux Klan of the 20th century. Their hatred of all that is good and sweet and human and pure is beyond all ability to understand. Their daily constant attacks upon millions and millions of Americans, as well as billions of humans the world over, who don\'t happen to share their bigoted, cruel, monstrous, and utterly insane view of humanity is beyond anything television has ever seen. The lies they spout and the ridiculous lies they try to pass off as truth, such as the idea of "life after death" or "god" or "sin" or "the devil" is so preposterous that they actually seem mentally ill, so lost are they in their fantasy. Sane people know that religion is a drug and shouldn\'t let themselves get addicted to that type of fantasy. However, The 700 Club is in a class by itself. They are truly a cult. While I believe in freedom of speech, they way they spread hatred, lies, disinformation, and such fantastic ideas is beyond all limits. I hope that one day the American Psychiatric Association will finally take up the study of those people who delude themselves in this way, people who let themselves sink so deeply into the fantasy land of religion that they no longer have any real concept of reality at all. Treatment for such afflicted individuals is sorely needed in this country, as so many people have completely lost their minds to the fantasy of religion. The 700 Club though, is even more horrible as it rises to the legal definition of \'cult\' but due to The 700 Club\'s vast wealth (conned daily from the millions of Americans locked in their deceitful grip) they are above the law in this country. For those of you who have seen the movie "The Matrix" you know that movie was a metaphor for religion on earth: the evil ones who are at the top of each of the religions who drain the ones they have trapped and cruelly abuse for their own selfish purposes, and those millions who are held in a death sleep and slowly being drained of their life force represent those many people who belong to religions and who have lost all ability to perceive what is really going on around them.In less civil times, the good townsfolk would have run such monsters as those associated with The 700 Club out of town with torches and pitchforks. But in today\'s world where people have lost all choice in their choices of television that is presented to them, we have no way to rid ourselves of the 700 Club plague. The television ratings system and the "V" chip on TV\'s should also have a rating called "R" for religion, so that rational people and concerned parents could easily screen such vile intellectual and brutal emotional rape, such as presented by The 700 Club every day all over our country, from themselves and their children.'

In [40]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [44]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [47]:
from nltk.corpus import stopwords
sw_list=stopwords.words('english')
new_df['review']=new_df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list])

/tmp/ipykernel_1448/289280008.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['review']=new_df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list])

In [49]:
new_df['review'].sample(3)

7833    [Iam, Big, fan, Mr, Ram, Gopal, Varma, could, ...
8141    [I, enjoy, film,, I, thought, ended, old, fash...
9082    [first, thought, bad, great, expectations, mov...
Name: review, dtype: object

In [52]:
X=new_df.iloc[:,0:1]

In [53]:
X.shape

(9983, 1)

In [55]:
y=new_df['sentiment']

In [56]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [57]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [59]:
X_train.shape

(6688, 1)

In [63]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [76]:
from sklearn.feature_extraction.text import CountVectorizer

def dummy(doc):
    return doc

cv = CountVectorizer(tokenizer=dummy, preprocessor=dummy, lowercase=False)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [77]:
print(cv.get_feature_names_out()[:10])

['\x10own' '!' '!!' '!!!' '!!!!' '!!!!!' '!!!!!!' '!!!!!!!!!' '!!!!!As'
 '!!!!!What']

In [78]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train_bow,y_train)

GaussianNB()

In [79]:
y_pred=gnb.predict(X_test_bow)
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6640364188163884

In [80]:
confusion_matrix(y_test,y_pred)

array([[1179,  472],
       [ 635, 1009]])

In [81]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [82]:
rf.fit(X_train_bow,y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8267071320182094

In [83]:
# Using TfIdf

In [102]:
def dummy(doc):
    return doc

In [103]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(tokenizer=dummy, preprocessor=dummy, lowercase=False)

In [104]:
X_train_tfidf=tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf=tfidf.transform(X_test['review'])

/usr/local/lib/python3.12/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [105]:
rf2=RandomForestClassifier()

In [106]:
rf2.fit(X_train_tfidf,y_train)

RandomForestClassifier()

In [107]:
y_pred=rf.predict(X_test_tfidf)

In [111]:
from sklearn.metrics import accuracy_score

In [113]:
accuracy_score(y_test,y_pred)

0.49893778452200305

# Practical Approaches

1.Always go for Ensemble learning

2.Do use Heuristic approach

3.Try ML baesd first then go to DL

4.Make sure to handle Imbalanced data

5.Do projects